

============================== 2024-06-07 10:40:12.539843 | e3bc1b95-4b57-4d63-ae5e-ac4ada1d0609 ==============================
[0m10:40:12.539843 [info ] [MainThread]: Running with dbt=1.3.7
[0m10:40:12.541641 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': 'C:\\Users\\marvin.edorh_artefac\\.dbt', 'send_anonymous_usage_stats': True, 'event_buffer_size': 100000, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'config_dir': False, 'which': 'debug', 'indirect_selection': 'eager'}
[0m10:40:12.541641 [debug] [MainThread]: Tracking: tracking
[0m10:40:12.542642 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207FA574E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207FA574D30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207FA574C70>]}
[0m10:40:14.038562 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207FA574AF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207FA574A60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000207FA574610>]}
[0m10:40:14.039559 [debug] [MainThread]: Flushing usage events
[0m10:40:14.476175 [error] [MainThread]: Encountered an error:
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
[0m10:40:14.518006 [error] [MainThread]: Traceback (most recent call last):
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\main.py", line 135, in main
    results, succeeded = handle_and_check(args)
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\main.py", line 198, in handle_and_check
    task, res = run_from_args(parsed)
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\main.py", line 245, in run_from_args
    results = task.run()
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\task\debug.py", line 109, in run
    self.test_configuration()
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\task\debug.py", line 281, in test_configuration
    profile_status = self._load_profile()
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\task\debug.py", line 252, in _load_profile
    profile: Profile = Profile.render_from_args(self.args, renderer, profile_name)
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\config\profile.py", line 426, in render_from_args
    return cls.from_raw_profiles(
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\config\profile.py", line 392, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\config\profile.py", line 346, in from_raw_profile_info
    credentials: Credentials = cls._credentials_from_profile(
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\config\profile.py", line 179, in _credentials_from_profile
    cls = load_plugin(typename)
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\adapters\factory.py", line 201, in load_plugin
    return FACTORY.load_plugin(name)
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\adapters\factory.py", line 56, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\adapters\snowflake\__init__.py", line 2, in <module>
    from dbt.adapters.snowflake.connections import SnowflakeConnectionManager  # noqa
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\dbt\adapters\snowflake\connections.py", line 17, in <module>
    import snowflake.connector
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\snowflake\connector\__init__.py", line 16, in <module>
    from .connection import SnowflakeConnection
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\snowflake\connector\connection.py", line 24, in <module>
    from . import errors, proxy
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\snowflake\connector\errors.py", line 19, in <module>
    from .telemetry_oob import TelemetryService
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\snowflake\connector\telemetry_oob.py", line 19, in <module>
    from .vendored import requests
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\snowflake\connector\vendored\requests\__init__.py", line 119, in <module>
    from ..urllib3.contrib import pyopenssl
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\snowflake\connector\vendored\urllib3\contrib\pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\OpenSSL\crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "c:\users\marvin.edorh_artefac\anaconda3\lib\site-packages\OpenSSL\crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

